### ISSUE TITLE
V-Loket commentaren, vragen en suggesties (1)

### ISSUE THREAD

**Issue by chrisverheyden** [Informatievlaanderen/OSLOthema-feitelijkeVerenigingen#1]
1. Algemene opmerkingen:		
1.1	Bijkomende eigenschappen/attributen toevoegen	
1.2	Beschrijvingen zijn te summier en beschrijven zelden de doelstelling of functie van een entiteit. 	
1.3	Typos uit beschrijvingen halen	
		
2. Data entiteiten		
2.1	Activiteit	
2.1.1		Wat is het doel van "Activiteit" (of is het activiteitstype)? Is dit een classificatie voor vereniging?
2.2	FeitelijkeVereniging	
2.2.1		Relaties tussen verenigingen ontbreekt. Dit kan ook gebruikt worden voor parent-child relatie
2.2.2		Indien adres niet beschikbaar dan ook Werkingsgebied: Plaats toevoegen aan FV (cfr. PubliekeOrganisatie)
2.2.3		FeitelijkeVereniging::isDeelVan -> oplossen via entiteit "Relatie"
2.2.4		Suggestie voor hernoeming: FeitelijkeVereniging::adress -> locatie met relatie naar adres
2.3	Erkenning	
2.3.1		Aan erkenning ook bewijs toevoegen of linken. (als er geen erkenningsaanvraag meer is, is bewijs ook weg)
2.3.2		Erkenning: uitbreiding naar niet alleen door publieke organisaties maar ook prive bvb banken
2.3.3		Data element "Gevolg" in erkenning: niet beter: "Beslissing" ?
2.4	Geregistreerde organisatie	
2.4.1		Geregistreerde organisatie: wat is het nut hiervan? Is dit voor bvb VZWs? 
2.4.2		Geregistreerde organisatie: is het niet beter om deze organisatie te combineren met FeitelijkeVereniging en een parent-child relatie op te zetten? 
2.4.3		IsDeelVan relatie: suggestie om hier de universelere oplossing van Relatie entiteit te gebruiken.
2.4.4		Voor organisatie: zie ook OVO organisatiemodel (organisatie register JSON)
2.5	Agent	
2.5.1		Waarom niet Vertegenwoordiger noemen? 
2.6	Contact	
2.6.1		Contacttype toevoegen aan contactinfo (persoonlijk, boekhouding, business, facturatie…)
2.6.2		Adres als aparte data entiteit of link naar adressenregister
2.6.3		Contact kan ook opgevat worden als een lijst van meerdere contactitems van verschillend types (email, tel, adres, twitter, whatsapp, facebook, linkedin…) om dit meer future-proof te maken
2.7	Erkenningsaanvraag	
2.7.1		Suggestie voor hernoeming: Erkenningsaanvraag::input -> "Bewijsmateriaal"
		
2.8	PubliekeDienstverlening	
2.8.1		Moet hier geen naam en beschrijving bij als data elementen?
2.8.2		Wat is het type: er zijn 2 types: bestellingen (real-time, bvb verhuur materiaal) en aanvragen (langdurend, bvb subsidies, premies...)
2.8.3		Kost of prijs? Is waarschijnlijk ook complexere data entiteit (prijs per eenheid, etc. Zie verhuur van tenten). Misschien beter verwijzen naar producten of diensten waar kosten worden gedefinieerd. Is Kost geen data type? 
2.8.4		Suggestie voor andere benaming van "vereist" of link naar entiteit: bvb. Voorwaarden of condities
2.8.5		Link naar product of dienst - zie ook IPDC
		
3. Aanbeveling om volgende data entiteiten toe te voegen		
3.1	Lid	
3.1.1		Vertegenwoordiger wordt dan child van Lid
3.2	Mandaat	
3.2.1		Mandaat moet kunnen toegevoegd aan vertegenwoordiger
3.3	Adres	
3.3.1		Adres als aparte data structuur (entiteit), dus niet in contact opnemen; zodoende kan adres hergebruikt bij locatie van vereniging
3.4	Bewijsstuk	
3.4.1		Een bewijs kan uit verschillende stukken bestaan: dus best link met bewijsstukken als aparte entiteit

**Comment by jeroen-devlieghere** [comment]
> Aanbeveling om volgende data entiteiten toe te voegen
> 3.1 Lid
> 3.1.1 Vertegenwoordiger wordt dan child van Lid

Dit stemt niet altijd overeen met de realiteit. 
Bv.: een oud-leider van een Chiro kan voor de organisatie nog allerlei hand- en spandiensten leveren en dus de facto een functie opnemen, terwijl hij/zij formeel gezien geen lid meer is. 

Het is natuurlijk altijd mogelijk dat die oud-leider in juridische zin de facto als lid van de feitelijke vereniging wordt beschouwd, doordat hij handelingen stelt in naam van - dan is de voorgestelde relatie wel altijd van toepassing.
Verder uit te klaren wat mij betreft.

**Comment by jeroen-devlieghere** [comment]
> 3.2 Mandaat
> 3.2.1 Mandaat moet kunnen toegevoegd aan vertegenwoordiger

Er is in OSLO al het vocabularium 'mandaat' en het AP 'Mandatendatabank', maar dat is expliciet gericht op het concept politiek mandataris (_De bevoegdheid om gedurende een bepaalde periode een bestuursorgaan te vormen of er deel van uit te maken. Een mandaat kan één of meerdere zetels voorstellen._), er lijkt geen meer algemeen geformuleerde superclass oid te zijn. daar lopen we dan vast.
