### ISSUE TITLE
kandidaat-standaard applicatie en eindrapport

### ISSUE THREAD

**Issue by stijnmichielsen** [Informatievlaanderen/OSLOthema-feitelijkeVerenigingen#10]
Graag geven we via deze weg onze aanvullingen op de kandidaat-standaard applicatie en het eindrapport:

Kandidaat-standaard applicatie:

- "Klasse < “Erkenning”:
De aanduiding door een bevoegde instelling waarbij wordt vastgesteld dat een vereniging aan bepaalde eisen voldoet, al dan niet tijdelijk."
_Het is voor ons niet duidelijk of het hier om een nieuw op te richten publiekrechtelijk bevoegde instelling zal gaan. Zal er een actieve rechtshandeling vereist zijn waarbij een formele erkenning wordt toegekend aan een vereniging?_

- "Klasse < “OSLO-Generiek::Agent”:
Iemand die of iets dat kan handelen of een effect kan teweeg brengen."
_Wijst 'iets dat' op een voorwerp of gaat het om een digitale tool die kan handelen of een effect kan teweegbrengen? 'Iets dat' is een erg ruime en abstracte verwoording_

- "Klasse < “Organisatie:GeregistreerdeOrganisatie”:
Organisatie met een juridisch statuut vastgelegd door registratie. Vergelijk met een formele organisatie waarbij dit statuut ook op een andere manier verkregen kan zijn."
_Wat dient begrepen te worden onder juridisch statuut? Gaat het om een erkenning op basis van specifieke bestaande wetgeving of is dit nieuwe wetgeving die zich hiervoor zal moeten ontwikkelen? Hoe is de verhouding van deze Vlaamse wetgeving ten opzichte van het Wetboek van Vennootschappen en Verenigingen?_

Eindrapport:

- De praktijkvoorbeelden in het rapport kunnen uitgebreid worden met voorbeelden uit de culturele sector. Ook in de culturele sector maken culturele verenigingen gebruik van accomodatie (zie oa. pagina 13): bijvoorbeeld een koor of harmonie die gebruik maakt van een ruimte voor hun repetities, opslag van materiaal of voorstellingen of bijv. een buurtwerking die een culturele activiteit organiseert in al dan niet publieke of private accomodatie (een lezing, bijeenkomst, concert, voorstelling in een buurthuis).

- Cultuurloket wordt geplaatst onder 'Koepelorganisaties' (zie pagina 33). Cultuurloket is echter geen echte koepelorganisatie en hoort in deze opsomming eerder onder 'Overige'.

**Comment by YvesMeersmans** [comment]
Om een goede opvolging te garanderen, raden we aan een apart issue te openen per opmerking. Dit zorgt ervoor dat de opmerkingen elk apart beter en makkelijker opgevolgd kunnen worden. 

- "Klasse < “Erkenning”: De erkenning zal in de eerste plaats gegeven worden door lokale besturen. Dit is inderdaad een actieve rechtshandeling. 

- "Klasse < “OSLO-Generiek::Agent”: Dit is express een erg ruime verwoording om op vele plaatsen van toepassing te zijn. Het gaat in dit geval over personen, organisaties... We verzoeken een issue te openen in de specifieke [OSLO-Generiek Github](https://github.com/Informatievlaanderen/OSLOthema-Generiek/issues). 

- "Klasse < “Organisatie:GeregistreerdeOrganisatie”: Het juridisch statuut komt overeen met welke [ondernemingsvormen](https://economie.fgov.be/nl/themas/ondernemingen/een-onderneming-oprichten/belangrijkste-stappen-om-een/het-juridische-statuut-voor) er bestaan. Er is op dit moment in de context van het traject OSLO Feitelijke Vereniging geen nieuwe wetgeving voorzien. 

De opmerkingen voor het eindrapport zijn goed ontvangen. Bedankt!
