### ISSUE TITLE
Onderscheid identificatie vereniging en erkenning/vergunning

### ISSUE THREAD

**Issue by LucMoens** [Informatievlaanderen/OSLOthema-feitelijkeVerenigingen#11]
Een VZW of een feitelijke vereniging an sich wordt niet erkend. Hebben jullie daar voorbeelden van? 
De VZW en ik neem aan ook feitelijke verenigingen worden  erkend/vergund voor één of meerdere activiteiten. 

Vb woonzorgcentrum X is erkend voor een dagcentrum, voor serviceflats, voor rusthuis… 
Een feitelijke vereniging, een carnavalgroep, kan vergund worden voor het houden van een eetfestijn, voor deelname aan de carnavalstoet, om aan de wagens te werken in de carnavalshallen. 
Dus er is een onderscheid tussen de vereniging en de activiteit waarvoor die erkend is.  
Als de vereniging maar één erkenning heeft lijkt het alsof de erkenning en vereniging samenvallen. 

 Zie https://publiek.departementwvg.be/cobrha/ hoe wij dit georganiseerd hebben. De VZW wordt niet erken, wel voor verschillende activiteiten.

**Comment by jeroen-devlieghere** [comment]
dit is gerelateerd aan #29 

Ik kan de redenering zeker volgen, weet alleen niet of Erkenningstype bij alle overheden die erkenningen verstrekken volledig samenvalt met hoe 'activiteit' gedefinieerd wordt, misschien hanteren ze soms andere indelingen. Dit moet wat mij betreft verder verkend worden.

**Comment by YvesMeersmans** [comment]
Er wordt een nieuwe definitie opgesteld die het onderscheid maakt tussen de feitelijke vereniging en de activiteit waarvoor die erkend is.

Nieuwe definitie: 
Erkenning = De aanduiding door een bevoegde instelling waarbij wordt vastgesteld dat de activiteit(en) van een persoon of instelling aan bepaalde eisen voldoet, al dan niet tijdelijk.
