### ISSUE TITLE
Definitie "vrijwilliger" nodig?

### ISSUE THREAD

**Issue by eveliendh** [Informatievlaanderen/OSLOthema-feitelijkeVerenigingen#12]
We voorzien een definitie voor een "feitelijke vereniging". Een vrijwilliger is een concept sterk gerelateerd aan de feitelijke vereniging. Is het noodzakelijk hierop te standaardiseren? Voorzien we dit in het model in opmaak?

**Comment by edrore** [comment]
In de meest recente versie van het model wordt geen gebruik meer gemaakt van ‘vrijwilliger’.
