### ISSUE TITLE
FeitelijkeVereniging: overerving van Organisatie overlapt

### ISSUE THREAD

**Issue by GeertThijs** [Informatievlaanderen/OSLOthema-feitelijkeVerenigingen#14]
**Beschrijving**:
FeitelijkeVereniging erft over van Organisatie, maar creëert nieuwe attributen voor attributen die Organisatie al heeft mn

- FeitelijkeVereniging.naam=Organisatie.voorkeursnaam (met resp datatype String vs Taalstring).
- FeitelijkeVereniging.activiteit=Organisatie.activiteit
- FeitelijkeVereniging.adres=Organisatie.contactinfo>Contactinfo.adres.

Standaard zijn hier twee opties: overerven (als het attribuut zonder meer bruikbaar is) of redefine (als het overgeërfde attribuut verder verfijnd moet worden)

**Oplossing**:
Overerven (met ^-teken voor de attribuutnaam aangezien de superklasse Organisatie niet op het diagram staat).

**Comment by YvesMeersmans** [comment]
Voorkeursnaam, activiteit en contactinfo worden overgeërfd worden voor de duidelijkheid vermeld in het model, terwijl Organisatie op het diagram staat.
