### ISSUE TITLE
Definitie van FeitelijkeVereniging

### ISSUE THREAD

**Issue by GeertThijs** [Informatievlaanderen/OSLOthema-feitelijkeVerenigingen#15]
**Beschrijving**:
De huidige definitie is:
- Een Feitelijke Vereniging bestaat uit twee of meerdere personen en/of organisaties, heeft geen rechtspersoonlijkheid en streeft een belangeloos doel na.

Commentaar:
- Begrip dat gedefinieerd wordt komt voor in de definitie
- Er staat niet in wat een FeitelijkeVereniging is (ttz een speciaal geval van een Organisatiea/Vereniging) maar waaruit ze bestaat (wat eerder een kenmerk is).
- Definities online (bv https://nl.wikipedia.org/wiki/Feitelijke_vereniging en https://www.vsdc.be/nl/faq/119/juridische-vragen/-wat-is-een-feitelijke-vereniging) spreken over een overeenkomst die zich niet op papier ofzo materialiseert en zelfs onuitgesproken kan zijn maar zich manifesteert in de daden van de Vereniging (in de feiten, vandaar het adjectief "feitelijk").
- Het feit dat een FeitelijkeVereniging eigenlijk een speciaal geval is van een Vereniging (zie issue #17 ) komt niet voor in de definitie.

**Oplossing**:
- Deze definitie:
  - Een Vereniging zonder rechtspersoonlijkheid, gebaseerd op een afspraak tussen twee of meerdere personen en/of organisaties om een belangeloos doel na te streven.
- En usageNote:
  - Een Vereniging wordt gedefinieerd als een Organisatie die een belangeloos doel nastreeft. Dat geldt ook voor een FeitelijkeVereniging, alleen heeft deze geen rechtspersoonlijkheid. Daardoor zijn de individuele leden van de FeitelijkeVereniging aansprakelijk voor de activiteiten die ze organiseren.

**Comment by jeroen-devlieghere** [comment]
>       (...) Daardoor zijn de individuele leden van de FeitelijkeVereniging aansprakelijk voor de activiteiten die ze organiseren.

is een detail, maar herformuleren als "Daardoor zijn de leden van de FeitelijkeVereniging **individueel aansprakelijk** voor de activiteiten die ze organiseren."
want bij feitelijke verenigingen speelt 'individuele' aansprakelijkheid, als juridisch concept, in tegenstelling tot bv. 'hoofdelijke' aansprakelijkheid van bestuurders bij vzw's.

**Comment by YvesMeersmans** [comment]
De definitie wordt aangepast. De vorige definitie gebruikte het begrip dat gedefinieerd wordt, wat inderdaad niet ideaal is bij het definiëren van zaken. Er wordt ook een Usage note toegevoegd. 

Nieuwe definitie: 
Feitelijke Vereniging = Een Vereniging zonder rechtspersoonlijkheid, gebaseerd op een afspraak tussen twee of meerdere personen om een onbaatzuchtig doel na te streven. 

Usage note: 
Een Feitelijke Vereniging is een Organisatie zonder rechtspersoonlijkheid die een onbaatzuchtig doel nastreeft. De individuele leden kunnen aansprakelijk zijn voor de activiteiten die ze organiseren.
