### ISSUE TITLE
Relatie met FormeleOrganisatie

### ISSUE THREAD

**Issue by GeertThijs** [Informatievlaanderen/OSLOthema-feitelijkeVerenigingen#16]
**Beschrijving**
Een FormeleOrganisatie (zie AP OSLO-Organisatie) is een erkende Organisatie. Maw: eens een FeitelijkeVereniging erkend is kan ze bijkomend getypeerd worden als FormeleOrganisatie. (Meervoudige classificatie: bij uitwisseling van een erkende FeitelijkeVereniging zeg je dat dan de Organisatie die je uitwisselt tegelijk een FeitelijkeVereniging en een FormeleOrganisatie is.)

Ter info de definitie ve FormeleOrganisatie:
- Een erkende organisatie, erkend in brede zin of meer specifiek in juridische zin met bijbehorende rechten en plichten.

Een FormeleOrganisatie heeft momenteel geen attributen, die krijgt ze pas als ze verder gespecialiseerd zou worden als GeregistreerdeOrganisatie (bv een VZW?). Maar als we ergens willen aangeven welke die erkenning is zouden we dat veld aan FormeleOrganisatie kunnen toevoegen.

**Oplossing**
Blijven bij het huidige model (met rechtstreekse relatie van de FeitelijkeVereniging naar de erkenning), maar toch verwijzen naar FormeleOrganisatie in de usageNote èn de klasse ook toevoegen aan het diagram. UsageNote van FeitelijkeVereniging wordt dan:
- Een Vereniging wordt gedefinieerd als een Organisatie die een belangeloos doel nastreeft. Dat geldt ook voor een FeitelijkeVereniging, alleen heeft deze geen rechtspersoonlijkheid. Daardoor zijn de individuele leden van de FeitelijkeVereniging zelf aansprakelijk voor de activiteiten die ze organiserern. OPMERKING: Van zodra de FeitelijkeVereniging erkend is kan ze bijkomend getypeerd worden als FormeleOrganisatie (zie elders in deze specificatie voor een definitie van deze term).

**Comment by eveliendh** [comment]
Om verwarring te vermijden is het een goed idee een erkende vereniging _niet_ als een formele organisatie te beschouwen. Bovendien kan een erkenning van een (feitelijke) vereniging tijdelijk zijn (bv voor een jaar). Dit terwijl de formele organisatie vaker voor de volledige levensduur van de organisatie erkend zal zijn. In overleg op basis van deze comment waren we al tot die conclusie gekomen, maar omwille van transparantie plaats ik ze hier nog eens.

**Comment by YvesMeersmans** [comment]
Een FormeleOrganisatie is gedefinieerd als volgt: Een erkende organisatie, 
erkend in brede zin of meer specifiek in juridische zin met bijbehorende rechten en 
plichten.

Een feitelijke vereniging is echter niet altijd erkend, en kan zijn erkenning verliezen na 
een zekere periode.

Een vaste typering tussen FormeleOrganisatie en FeitelijkeVereniging is daarom niet 
aangeraden. De tijdelijke typering vanuit FormeleOrganisatie is eveneens niet af te dwingen via het model.

Wel is het mogelijk om een Vereniging, als specialisatie van een Organisatie toe te voegen aan het model, en te definiëren.

Definitie: Vereniging = Een Organisatie die een onbaatzuchtig doel nastreeft.*

Dit geldt ook voor een FeitleijkeVereniging, alleen heeft een Feitelijke Vereniging geen rechtspersoonlijkheid. Daardoor zijn de individuele leden van de FeitelijkeVereniging zelf aansprakelijk voor de activiteiten die ze organiseren.

**Comment by GeertThijs** [comment]
De Oplossing vermeld bij de issue blijft dus dezelfde: wie dat wil kan dmv double typing (= meervoudige classificatie) at runtime (= bij uitwisseling) aangeven dat de FeitelijkeVereniging erkend is door ze bijkomend te typeren als FormeleOrganisatie.
