### ISSUE TITLE
Kardinaliteit relatie Erkenning(saanvraag) met FeitelijkeVereniging

### ISSUE THREAD

**Issue by GeertThijs** [Informatievlaanderen/OSLOthema-feitelijkeVerenigingen#18]
**Beschrijving**
De associaties Erkenning-FeitelijkeVereniging en Erkenningsaanvraag-FeitelijkeVereniging hebben een kardinaliteit 1. Wat suggereert dat een erkenning of erkenningsaanvraag altijd van toepassing is op een FeitelijkeVereniging. Hoewel ze gepubliceerd worden in de context van FeitelijkeVerenigingen zijn de definities van beide wel algemeen opgesteld, alsof ze op om het even welke Organisatie of zelfs Persoon kunnen slaan.

**Oplossing**
Kardinaliteit onbepaald zetten & attribuut toevoegen aan Erkenningsaanvraag en Erkenning met de Agent waarop de erkenning(saanvraag) slaat. (Waarbij impliciet duidelijk is dat een FeitelijkeVereniging onrechtstreeks een Agent is aangezien het een subklasse is van Organisatie en Organisatie een agent is.)

**Comment by YvesMeersmans** [comment]
De kardinaliteit is nu veranderd naar onbepaald.
