### ISSUE TITLE
Erkenningsaanvraag.geeftRechtOp associatie

### ISSUE THREAD

**Issue by GeertThijs** [Informatievlaanderen/OSLOthema-feitelijkeVerenigingen#19]
**Beschrijving**
De associatie Erkenningsaanvraag.geeftrechtOp met Erkenning vereist dat de Erkenning al wordt aangemaakt nog voor ze is toegekend.

De gevraagde geldigheidsperiode en type is dan deze die is aangevraagd maar als deze afwijkt van wat uiteindelijk wordt toegekend eindigen we met een erkenningsaanvraag waarvan niet meer geweten is voor welke periode en welk type de oorspronkjelijke aanvraag was, laat staan dat de toegekende periode en type nu slaat op alle aanvragen die er waren (want de kardinaliteit Erkenning-Erkenningsaanvraag is blijkbaar 0..*).

**Oplossing**
Als we dan toch de aanvragen apart willen bijhouden moeten periode en type ook bij de Erkenningsaanvraag staan. Inclusief voor wie de erkenning bedoeld is.

Ook de naam vd associatie moet dan wijzigen van geeftRechtOp naar bvb resultaat (van de aanvraag). Met kardinaliteit 0..1 want de aanvraag wordt niet noodzakelijk goedgekeurd.

Alternatief: statusveld toevoegen aan erkenning (met waarden aangevraagd, inbehandeling, toegekend, geweigerd) en erkenningsaanvraag schrappen.

**Comment by jeroen-devlieghere** [comment]
> De gevraagde geldigheidsperiode en type is dan deze die is aangevraagd maar als deze afwijkt van wat uiteindelijk wordt toegekend eindigen we met een erkenningsaanvraag waarvan niet meer geweten is voor welke periode en welk type de oorspronkjelijke aanvraag was (...)
> **Oplossing** Als we dan toch de aanvragen apart willen bijhouden moeten periode en type ook bij de Erkenningsaanvraag staan. Inclusief voor wie de erkenning bedoeld is.

Mee eens, want niet vergeten dat niet elke aanvraag altijd tot een erkenning leidt, dus ook een aanvraag zonder erkenning moet goed te interpreteren zijn.

**Comment by YvesMeersmans** [comment]
De naam van de associatie wordt gewijzigd van ‘geeftRechtOp’ naar ‘Resultaat’, met kardinaliteit 0..1. Niet elke aanvraag leidt steeds tot een erkenning. Een aanvraag zonder erkenning zal nu dus ook mogelijk zijn in het model. 

Verder worden Periode en Type bij Erkenningsaanvraag geplaatst, inclusief voor wie de Erkenning bedoeld is. Dit is nodig om bij te houden voor welke periode de erkenning is aangevraagd, en welk type erkenning is aangevraagd.
