### ISSUE TITLE
datatype 'erkenningstype' zit niet in het model? 

### ISSUE THREAD

**Issue by jeroen-devlieghere** [Informatievlaanderen/OSLOthema-feitelijkeVerenigingen#2]
in het datamodel wordt het attribuut 'type' van de entiteit 'erkenning' aangeduid als een DataType 'Erkenningstype', maar dit DataType zit niet in het model, en [er wordt ook niet doorgelinkt ](https://test.data.vlaanderen.be/doc/applicatieprofiel/FeitelijkeVerenigingen/ontwerpstandaard/2021-06-22#Erkenningstype) naar de definitie van dit datatype elders. 

Dat lijkt dus nog een los eindje? Of is dit een zelf te definiëren attribuut? hierrond zou dan wat meer houvast gegeven moeten worden denk ik

**Comment by jeroen-devlieghere** [comment]
aansluitend bij bovenstaande vraag/opmerking: in de workshops was ook aangegeven dat het nuttig kan zijn om te weten op welk niveau een erkenning is gebeurd (bv. op dienstniveau, of door CBS of gemeenteraad...). Aangezien deze informatie (deels) via LBLOD aangeleverd kan worden (uit de Lokale Besluiten dus), lijkt het zinvol dit informatie-element ook in het model op te nemen

**Comment by jeroen-devlieghere** [comment]
ten slotte nog een opmerking over attribuut 'type' van entiteit Erkenning: op dit moment geven we daar in feite een puur circulaire definitie aan: het 'type' van de erkenning is de 'aard' van de erkenning, waarbij 'type' en 'aard' synoniemen zijn. Dat lijkt me niet echt bij te dragen aan de semantische standaard

Nu zie je dit ook gebeuren in andere, reeds gepubliceerde standaarden, zie bv. 'Type van agendapunt' in standaard 'Besluit Publicatie', dat wordt gedefinieerd als... 'type van agendapunt'. 
![afbeelding](https://user-images.githubusercontent.com/13114159/126605761-db053c5c-e197-4825-a64a-cd8f8dec658f.png)

**Comment by YvesMeersmans** [comment]
Dag Jeroen,

1) Dit wordt doorgaans zo gedaan, dat we codelijsten zo typeren en definiëren.

2) wordt deels gedekt door link met publieke organisatie (relatie toegekendDoor); maar er kan inderdaad een complexe relatie van gemaakt worden met een attribuut dat het "werkingsniveau" aanduidt.

3) Een type wordt doorgaans zo aangegeven en beschreven in OSLO. Heb je een voorstel voor een alternatief?

**Comment by YvesMeersmans** [comment]
Er wordt een nieuwe definitie opgesteld. Erkenningstype = geeft meer informatie over de categorie waaronder de erkenning valt.
