### ISSUE TITLE
Attribuering PubliekeOrganisatie

### ISSUE THREAD

**Issue by GeertThijs** [Informatievlaanderen/OSLOthema-feitelijkeVerenigingen#20]
**Beschrijving**
Een PubliekeOrganisatie is een Organisatie. Maar omdat Organisatie in het diagram ontbreekt (om redenen van leesbaarheid) is het gebruikelijk de relevante overgeërfde attributen toe te voegen (met een ^-teken voor de naam om aan te geven dat ze overgeërfd zijn).

De PubliekeOrganisaties waarover het hier gaat zullen meestal GeregistreerdeOrganisaties zijn. Dit kan aangegeven worden in de uitwisseling dmv double typing. In dat geval krijgt het uitgewisselde dataobject er nog GeregistreerdeOrganisatie.identificator bij en vervangt GeregistreerdeOrganisatie.wettelijkeNaam het overgeërfde PubliekeOrganisatie.^voorkeursnaam.

**Oplossing**
Attribuut ^voorkeurnaam toevoegen. Opmerking toevoegen aan usagenote van PubliekeOrganisatie ivm double typing. De klasse GeregistreerdeOrganisatie is al aanwezig. Zie ook issue #16.

**Comment by jeroen-devlieghere** [comment]
> De PubliekeOrganisaties waarover het hier gaat zullen meestal GeregistreerdeOrganisaties zijn. 

dit volg ik niet. Ik had begrepen dat met GeregistreerdeOrganisatie koepels e.d. bedoeld werd, zoals bv. de Chiro of de Broeders van Liefde oid. Hoe kunnen PubliekeOrganisaties daar een deelverzameling van zijn?

**Comment by YvesMeersmans** [comment]
De klasse Organisatie wordt toegevoegd.
