### ISSUE TITLE
Datatype van GeregistreerdeOrganisatie.^Vestiging

### ISSUE THREAD

**Issue by GeertThijs** [Informatievlaanderen/OSLOthema-feitelijkeVerenigingen#22]
**Beschrijving**
Het datatype van GeregistreerdeOrganisatie.^vestiging is MaatschappelijkeZetel, een type Vestiging dat elders in het model niet gedefinieerd is.

**Oplossing**
Het is gebruikelijk om voor de MaatschappelijkeZetel de associatie Organisatie.heeftPrimaireVestiging (met datatype Vestiging).

**Comment by YvesMeersmans** [comment]
Het attribuut ‘heeftPrimaireVestiging’ is opgenomen bij de toegevoegde klasse OSLO-Organisatie::Organisatie. Die Vestiging heeft ook een vestigingsAdres.
