### ISSUE TITLE
Nut van associatieklasse HeeftVerantwoordelijke

### ISSUE THREAD

**Issue by GeertThijs** [Informatievlaanderen/OSLOthema-feitelijkeVerenigingen#24]
**Beschrijving**
De associatieklasse HeeftVerantwoordelijke (momenteel is de naam verkeerdelijk heeftVerantwoordelijke) lijkt overbodig. Doel vd klasse is om de rol van de geassocieerde Agent te benoemen maar die rol zit al in de naam vh element ("verantwoordelijke"). 

**Oplossing**
De huidige relatie FeitelijkeVereniging-Agent volstaat. Deze wel benoemen, bv FeitelijkeVereniging.verantwoordelijke.

**Comment by GeertThijs** [comment]
Misschien toch beter laten, laat toe om op te geven welke verantwoordelijkheid de persoon binnen de FeitelijkeVereniging heeft. Maar in dat geval is hergebruik van Hoedanigheid uit OSLO-Organisatie aangewezen. In dat geval echter herbruiken we beter de klasse Positie uit OSLO-Organisatie, waarvan we een klasse Verantwooordelijkheid kunnen laten overerven. Opmerking: Positie is geen associatieklasse.

**Comment by jeroen-devlieghere** [comment]
deze issue lijkt gerelateerd aan #32

**Comment by YvesMeersmans** [comment]
Deze associatieklasse blijft behouden omdat die toelaat om op te geven 
welke verantwoordelijkheid de persoon binnen de FeitelijkeVereniging heeft. De
benaming van de klasse verandert wel van HeeftVerantwoordelijke naar Verantwoordelijke. Ter verduidelijking zal “Hoedanigheid” uit  OSLO-Organisatie hergebruikt worden. Met  Hoedanigheid wordt een ‘Agent met een positie’ bedoeld. Hoedanigheid laat een functie toe om te handelen. Meer informatie over de klasse Hoedanigheid uit OSLO-Organisatie kan [hier](https://data.vlaanderen.be/doc/applicatieprofiel/organisatie-basis/#Hoedanigheid) geraadpleegd worden.
