### ISSUE TITLE
Attribuering PubliekeDienstverlening

### ISSUE THREAD

**Issue by GeertThijs** [Informatievlaanderen/OSLOthema-feitelijkeVerenigingen#26]
**Beschrijving**
Enig attribuut momenteel is (het optionele) kost. Echter, het AP Dienstencataloog suggereert nog een aantal verplichte velden: naam en beschrijving.

**Oplossing**
Deze attributen toevoegen aan PubliekeDienstverlening.

**Comment by jeroen-devlieghere** [comment]
Ik heb nog een algemene vraag over het AP Dienstencataloog: daar lees ik "Dit is een applicatieprofiel op het [OSLO-Dienst vocabularium](https://data.vlaanderen.be/ns/dienst). ", echter, op de pagina waarnaar verwezen wordt, vind ik geen vocabularium... En de link [Verken het vocabularium](http://visualdataweb.de/webvowl/#iri=https://data.vlaanderen.be/ns/dienst.ttl) op de pagina over 'Vocabularium dienst' geeft een foutmelding.

Staat het vocabularium 'Dienst' dus enkel opgelijst op de AP-pagina Dienstencataloog? dat vind ik verwarrend.

**Comment by GeertThijs** [comment]
De link [https://data.vlaanderen.be/ns/dienst](https://data.vlaanderen.be/ns/dienst) in jouw bericht werkt nochtans. Verken het vocabularium werkt inderdaad niet meer, we zijn daar afhankelijk ve dienst die niet meer bestaat of verplzaatst is. In meer recente vocabularia is deze link geschrapt. Het vocabularium is ook apart te vinden in het [OSLO standaardenregister](https://data.vlaanderen.be/standaarden/).

**Comment by edrore** [comment]
Zoals in de comment hierboven werd vermeld, zijn de verplichte attributen 'naam' en 'beschrijving' opgenomen in het applicatieprofiel. Het toevoegen van extra attributen aan de klasse PubliekeDienstverlening is mogelijk in de implementatie fase.
