### ISSUE TITLE
Relatie PubliekeOrganisatie-erkenningsaanvraag

### ISSUE THREAD

**Issue by GeertThijs** [Informatievlaanderen/OSLOthema-feitelijkeVerenigingen#27]
**Beschrijving**
De associatie van PubliekeOrganisatie-Erkenningsaanvraag wordt beter omgedraaid. Nu voegen we met PubliekeOrganisatie.controleert een kenmerk toe aan PubliekeOrganisatie, terwijl we gewoon willen zeggen dat de erkenningsaanvraag door een PubliekeOrganisatie wordt gecontroleerd.

Bovendien is er een gelijkaardige maar wel omgekeerde relatie tussen erkenning en PubliekeOrganisatie (mn Erkenning.toegekendDoor). Het is beter om hiermee te aligneren

**Oplossing**
De associatie PubliekeOrganisatie.controleerd vervangen door de associatie erkenningsaanvraag.wordtgecontroleerdDoor.

**Comment by jeroen-devlieghere** [comment]
Eens met de opmerking om associaties van PubliekeOrganisatie naar Erkenningsaanvraag en Erkenning te aligneren. 

Zelf heb ik er moeite mee dat sommige associaties actief geformuleerd worden (+dientIn, +vraagtAan, +controleert), terwijl andere passief geformuleerd worden (+toegekendDoor). Is hier een algemene OSLO-richtlijn rond? Want actief vs. passief draait de richting om (X controleert Y vs Y wordt gecontroleerd door X)

**Comment by YvesMeersmans** [comment]
De associatie ‘PubliekeOrganisatie controleert’ wordt vervangen door de associatie ‘Erkenningsaanvraag aangevraagdBij’.
