### ISSUE TITLE
Gegevens 'contactpersoon'/'agent' naar 'organisatie' verplaatsen

### ISSUE THREAD

**Issue by edrore** [Informatievlaanderen/OSLOthema-feitelijkeVerenigingen#28]
Bepaalde gegevens die bij Contactpersoon/Agent staan, kunnen eventueel naar Organisatie verplaatst worden. Bv.: website staat bij Agent, maar het zou logischer zijn moest dit bij Organisatie geplaatst worden. 'E-mail' en 'Telefoon' kunnen dan bij de Contactpersoon blijven staan.

**Comment by GeertThijs** [comment]
Een Persoon kan ook een website hebben.

**Comment by jeroen-devlieghere** [comment]
En omgekeerd: een organisatie kan ook een algemeen e-mailadres en een algemeen telefoonnr hebben (hoe groter de organisatie, hoe meer kans daartoe), deze eigenschappen zijn van praktische waarde. 

De persoonlijke website van een Persoon lijkt me niet zo relevant in deze optiek.

**Comment by YvesMeersmans** [comment]
Contactinfo staat nu zowel bij de klasse FeitelijkeVereniging gemodelleerd, als bij de klasse Organisatie. Deze Contactinfo volstaat, zaken zoals ‘website’ of ‘telefoonnummer’ hoeven daardoor niet specifiek vermeld te worden in de klassen.
