### ISSUE TITLE
Definitie Activiteit

### ISSUE THREAD

**Issue by edrore** [Informatievlaanderen/OSLOthema-feitelijkeVerenigingen#29]
De definitie van Activiteit zou verder uitgewerkt moeten worden, evenuteel via een subklasse. Activiteit wordt gezien als het domein waarbinnen een Feitelijke Vereniging actief is, en niet als het soort werking dat de Feitelijke Vereniging aanbiedt.

**Comment by GeertThijs** [comment]
Een enumeratie is daarvoor beter geschikt. De lijst met potentiële activiteiten wijzigt sneller in de tijd dan het model.

**Comment by jeroen-devlieghere** [comment]
zoals Eva aangeeft: we willen 'activiteit' als aanduiding van algemeen werkingsdomein van een organisatie, dat is niet iets wat zo snel uitbreidt normaal gezien, als dit breed genoeg wordt opgezet. Neemt niet weg dat het best geen gesloten lijst wordt, maar dat die uitbreidbaar blijft, inderdaad.  

Wanneer we de eigenschap 'activiteit' geen concrete vulling geven, dan zal de definitie gegarandeerd aanleiding geven tot uiteenlopende interpretaties, wegens zeer algemeen. In het applicatieprofiel 'Doelgericht Digitaal Transformeren' (nog in ontwikkeling) stuurt men aan op een àndere invulling van het concept Activiteit (een andere subclass dus?)

Merk in dat verband op dat in het OSLO-model 'organisatie' naar de externe term 'Organisatieactiviteit' van W3C verwijst, en dat daarover te lezen valt: 
_The activity of a company should be recorded using a controlled vocabulary expressed as a SKOS concept scheme. Several such vocabularies exist, many of which map to the UN's ISIC codes. Where a particular controlled vocabulary is in use within a given context, such as SIC codes in the UK, it is acceptable to use these, however, the preferred choice for European interoperability is NACE_
--> dat wijst dus in de richting van NACEBEL als onderlegger van deze oefening.

**Comment by jeroen-devlieghere** [comment]
gerelateerd aan #14

**Comment by YvesMeersmans** [comment]
We hebben voorlopig het attribuut activiteit uit OSLO Organisatie overgenomen. https://data.vlaanderen.be/doc/applicatieprofiel/organisatie-basis/#Organisatie%3Aactiviteit

Dit heeft echter een vaste definitie (namelijk "Type activiteit die door de organisatie wordt uitgeoefend."). Er wordt tevens een Usage note toegevoegd in het OSLO feitelijke verenigingen applicatieprofiel en voc.:
De activiteit van een feitelijke vereniging kan bv. zijn ‘jeugdvereniging’, ‘sportvereniging’, ‘seniorenvereniging’, … De feitelijke vereniging is actief in dit soort werking.

In een volgende stap moet bekeken worden of we dit verder willen aanpassen met een andere benaming van het attribuut (dus met een andere naam dan "activiteit"), om de verwarring waar eerder sprake van was te vermijden.

**Comment by YvesMeersmans** [comment]
Dit wordt verder gezet in issue 47.
