### ISSUE TITLE
Verantwoordelijke als een hoedanigheid eerder dan een positie?

### ISSUE THREAD

**Issue by eveliendh** [Informatievlaanderen/OSLOthema-feitelijkeVerenigingen#32]
Conform het OSLO applicatieprofiel organisatie lijkt verantwoordelijke eerder een hoedanigheid dan wel een positie. 

- een **hoedanigheid** is een "Agent met een positie"; 
"Laat een functie toe om te handelen,bv ihkv een dienstverlening (bv diversiteitsplan wordt opgemaakt door diversiteitsambtenaar)." 
- een **positie** verwijst eerder naar een functie, zie ook: https://data.vlaanderen.be/doc/applicatieprofiel/organisatie-basis/#Positie

**Comment by GeertThijs** [comment]
Zou inderdaad beter zijn. De associatie Verantwoordelijke.verantwoordelijke met Agent vervalt dan aangezien een Hoedanigheid niet enkel een Positie maar ook een Agent is (en er dus de attributen van overerft).

**Comment by YvesMeersmans** [comment]
Deze associatieklasse blijft behouden omdat die toelaat om op te geven 
welke verantwoordelijkheid de persoon binnen de FeitelijkeVereniging heeft. De
benaming van de klasse verandert wel van HeeftVerantwoordelijke naar Verantwoordelijke. Ter verduidelijking zal “Hoedanigheid” uit  OSLO-Organisatie hergebruikt worden. Met  Hoedanigheid wordt een ‘Agent met een positie’ bedoeld. Hoedanigheid laat een functie toe om te handelen. Meer informatie over de klasse Hoedanigheid uit OSLO-Organisatie kan [hier](https://data.vlaanderen.be/doc/applicatieprofiel/organisatie-basis/#Hoedanigheid) geraadpleegd worden.
