### ISSUE TITLE
Kardinaliteit op associatie FeitelijkeVereniging heeftLid Agent

### ISSUE THREAD

**Issue by jeroen-devlieghere** [Informatievlaanderen/OSLOthema-feitelijkeVerenigingen#33]
de kardinaliteit op +heeftLid is nu 1..*, wat volgens mij betekent dat iedere FeitelijkeVereniging minstens 1 lid heeft, maar dat klopt niet met de nieuwe vennootschapswet, die bepaalt dat een feitelijke vereniging minstens uit 2 leden moet bestaan

**Oplossing**
de kardinaliteit FeitelijkeVereniging-Agent op associatie heeftLid aanpassen naar 2..*

**Comment by YvesMeersmans** [comment]
Deze kardinaliteit is nu aangepast naar 2..*
