### ISSUE TITLE
Relatie tussen PubliekeDienstverlening en Erkenning

### ISSUE THREAD

**Issue by jeroen-devlieghere** [Informatievlaanderen/OSLOthema-feitelijkeVerenigingen#36]
In het model wordt 'erkenning' benaderd als iets buiten PubliekeDienstverlening, ik denk dat veel overheden erkenningen integendeel zien als daar inherent deel van uitmakend. Als je naar het [AP ](https://data.vlaanderen.be/doc/applicatieprofiel/dienstencataloog/)kijkt, dan zie ik ook weinig inhoudelijke redenen om erkenning erbuiten te houden, de elementen die we nodig hebben, zitten daar al in (bewijs, criteriumvereiste, gebeurtenis, formeelkader, procedure, enz.)

Erkenning als een vorm van PubliekeDienstverlening beschouwen zou ook helpen om GeregistreerdeOrganisatie in het verhaal te krijgen, want zij hebben even goed erkenningen nodig. vanuit het V-loket bekeken is er wat dat betreft geen verschil tussen een vzw of een feitelijke vereniging (in die zin was de scope van dit OSLO-traject mss wat te beperkt, we operationaliseren nu wel feitelijke verenigingen, maar niet de geregistreerde organisaties terwijl we die even goed targetten).

**Comment by jeroen-devlieghere** [comment]
aanvulling: voor sommige instanties is de term 'erkenning' inwisselbaar met 'vergunning' (bv. bij MOW), dat is een extra argument om 'erkenning' te laten aansluiten bij PubliekeDienstverlening

**Comment by jeroen-devlieghere** [comment]
aanvulling, vanuit overleg 25-1-22 met OSLO-tracks 'jeugd en infrastructuur' en 'doelgericht digitaal transformeren': class erkenning wordt best op een hoger niveau in de OSLO-hiërarchie uitgewerkt, want komt ook in veel andere contexten terug, met dezelfde algemene invulling. 
Verder heeft 'erkenning' ook een link met AP 'besluitvorming' (erkenning is meestal/altijd een overheidsbesluit, op basis van een bepaalde rechtsgrond); dit dient ook nog beter ingebed te worden. Jitse De Cock ging dit verder opnemen binnen OSLO

**Comment by edrore** [comment]
Erkenning zal een specialisatie worden van Output uit OSLO Dienst-Transactiemodel. Erkenningsaanvraag erft over van PubliekeDienstverlening-Consumptie. Via deze link wordt OSLO-Dossier in het model meegenomen.
