### ISSUE TITLE
Onduidelijkheid over 'Activiteit'

### ISSUE THREAD

**Issue by edrore** [Informatievlaanderen/OSLOthema-feitelijkeVerenigingen#37]
De definitie van het attribuut 'Activiteit' zorgt voor verwarring. Het moet duidelijker worden dat dit slaat op het activiteittype (bv. jeugdactiviteiten, sportactiviteiten, cultuur, ...).

**Comment by jeroen-devlieghere** [comment]
cfr. afstemming 25-1-22 met andere OSLO-trajecten: conclusie was volgens mij om attribuut 'activiteit' af te leiden uit attribuut 'activiteit' van OSLO-organisatie, dus wordt van het type 'OrganisatieActiviteit'. Maar desambiguering met 'activiteit' in betekenis 'concreet event' blijft nodig, de definities bieden nu te weinig houvast.

**Comment by YvesMeersmans** [comment]
We hebben voorlopig het attribuut activiteit uit OSLO Organisatie overgenomen. https://data.vlaanderen.be/doc/applicatieprofiel/organisatie-basis/#Organisatie%3Aactiviteit

Dit heeft echter een vaste definitie (namelijk "Type activiteit die door de organisatie wordt uitgeoefend."). Er wordt tevens een Usage note toegevoegd in het OSLO feitelijke verenigingen applicatieprofiel en voc.:
De activiteit van een feitelijke vereniging kan bv. zijn ‘jeugdvereniging’, ‘sportvereniging’, ‘seniorenvereniging’, … De feitelijke vereniging is actief in dit soort werking.

In een volgende stap moet bekeken worden of we dit verder willen aanpassen met een andere benaming van het attribuut (dus met een andere naam dan "activiteit"), om de verwarring waar eerder sprake van was te vermijden.

**Comment by eveliendh** [comment]
zie issue #47

**Comment by YvesMeersmans** [comment]
Dit wordt verder gezet in issue 47.
