### ISSUE TITLE
Onduidelijkheid over 'adresvoorstelling'

### ISSUE THREAD

**Issue by edrore** [Informatievlaanderen/OSLOthema-feitelijkeVerenigingen#39]
Adresvoorstelling moet nagekeken worden: is dit juist gemodelleerd en overgenomen uit de respectievelijke OSLO standaard?

**Comment by YvesMeersmans** [comment]
@michael-mampaey Kan jij aub bevestigen of wij _Adresvoorstelling_ juist gemodelleerd hebben?

**Comment by michael-mampaey** [comment]
@YvesMeersmans Dit is in orde.
