### ISSUE TITLE
rekeningnummer

### ISSUE THREAD

**Issue by bemelmwa** [Informatievlaanderen/OSLOthema-feitelijkeVerenigingen#4]
In het applicatieprofiel vind ik niets terug mbt rekeningnummer.  Is er een reden waarom dit niet opgenomen werd ?

**Comment by eveliendh** [comment]
Zou ik ook opnemen!

**Comment by jeroen-devlieghere** [comment]
Mee eens. er dan rekening mee houden dat een organisatie ook meerdere rekeningnummers kan hebben.

**Comment by YvesMeersmans** [comment]
Bankrekeningnummer wordt opgenomen als attribuut onder de klasse FeitelijkeVereniging. Het wordt zo gemodelleerd dat een bankrekeningnummer niet verplicht is.

**Comment by YvesMeersmans** [comment]
We maken het bankrekeningnummer niet verplicht omdat in bepaalde use cases of uitwisselingen een bankrekeningnummer niet vereist is. Daarnaast is bij de oprichting van een feitelijke vereniging vaak nog geen bankrekeningnummer gekend. De verstrenging kan gebeuren bij de implementatie van de authentieke bron.
