### ISSUE TITLE
Relatie lijkt te ontbreken tussen Erkenning en PubliekeDienstverlening

### ISSUE THREAD

**Issue by YvesMeersmans** [Informatievlaanderen/OSLOthema-feitelijkeVerenigingen#42]
Er lijkt een belangrijke relatie te missen tussen ‘Erkenning’ en ‘PubliekeDienstverlening’, nl. ‘erkenning geeft recht op publieke dienstverlening’. Dat is nl. de reden waarom overheden die erkenningsprocedures opzetten, om te kunnen bepalen wie wel/niet van bepaalde dienstverlening (bv. ook subsidies) gebruik mag maken. Dat zouden we ook in het V-loket kunnen operationaliseren via Informeren op maat: een vereniging ziet dan meteen of ze al gebruik kunnen maken van een bepaalde dienst, dan wel of ze eerst haar erkenning in orde moet brengen.

**Comment by YvesMeersmans** [comment]
Deze relatie is echter al afgedekt door de relatie via PubliekeOrganisatie. Er moet geen expliciete relatie tussen Erkenning en PubliekeDienstverlening toegevoegd worden. 

![image](https://user-images.githubusercontent.com/34094951/151026269-b283e18c-f397-41db-a513-50825edf7bef.png)

Op een meer technisch niveau (bij implementatie) zal er genavigeerd moeten worden via de klasse PubliekeOrganisatie. Daar moet de check gebeuren of een FeitelijkeVereniging een erkenning heeft voor de PubliekeOrganisatie kan overgaan tot het aanbieden van de PubliekeDienstverlening.

**Comment by jeroen-devlieghere** [comment]
ik kan deze redenering volgen. Ik heb gezien dat PubliekeDienstverlening een circulaire relatie 'vereist' heeft ("Publieke dienstverlening die voorafgaandelijk moet worden uitgevoerd om van de publieke dienstverlening gebruik te kunnen maken."), wat wel een noodzakelijke voorwaarde is. Dus dat lijkt me helemaal in orde.

![2022-01-25_20h41_20](https://user-images.githubusercontent.com/13114159/151048286-60830c45-b01d-43df-96db-b3f227747cfb.png)
!
