### ISSUE TITLE
relatie 'FeitelijkeVereniging isDeelVan/heeftDeelVereniging Feitelijke Vereniging': hernoemen

### ISSUE THREAD

**Issue by jeroen-devlieghere** [Informatievlaanderen/OSLOthema-feitelijkeVerenigingen#43]
deze issue loopt vooruit op de actualisering van het AP (cfr. voorgesteld schema op werkgroep 25-01-22):
 de verwoording 'is deel van' kan suggereren dat er hoofd-FV is, en een deel-FV, dat één FV m.a.w. de leiding heeft en de andere daarvan afhankelijk is; dit houdt wschl juridisch geen steek, want een FV is per definitie onafhankelijk. We laten dit nog dubbelchecken in het juridische traject.

indien dit klopt, wordt de relatie best hernoemd naar het neutralere 'isGelinktAan'.

**Comment by jeroen-devlieghere** [comment]
aanvulling hierop: er is ook de wens om in de unieke bron voor verenigingen subentiteiten ('afdelingen') van vzw's of feitelijke verenigingen op te nemen; dit omdat deze óók interacties aangaan met overheden, en omdat deze op dit moment nergens centraal geregistreerd worden (ook niet in KBO). Dit  vereist dus toevoeging van een andere entiteit aan het model (noem ze bv. 'afdeling') die wél de relatie isDeelVan (parent-child) kan hebben met een FV.
(deze behoefte leeft ook bij Departement WVG, die nu worstelen met het in kaart brengen van de zgn 'fijnmazigheid' van de verenigingen waarmee zij te maken hebben, cfr. interventies van Luc Moens in de werkgroep-bijeenkomsten)

**Comment by YvesMeersmans** [comment]
We hernoemen de relatie ‘isDeelVan’ naar ‘isGelinktAan’, om een meer generieke relatie tussen een Feitelijke Vereniging en een Geregistreerde Organisatie aan te geven. Er wordt een zelfrelatie bij Feitelijke Vereniging toegevoegd, om de parent-child relatie tussen Feitelijke Verenigingen toe te laten. Deze zelfrelatie laat toe dat feitelijke verenigingen onderdeel worden van elkaar: bv. een wielerclub uit Antwerpen en een wielerclub uit Wilrijk vormen één grotere feitelijke vereniging.

DCJM zal rond deze “zelfrelatie” bij de implementatie van het model de juridische aspecten en implicaties onderzoeken.

**Comment by jeroen-devlieghere** [comment]
Ik wil een aanvulling geven op wat ik in mijn vorige comment schreef:
>Dit vereist dus toevoeging van een andere entiteit aan het model (noem ze bv. 'afdeling') die wél de relatie isDeelVan (parent-child) kan hebben met een FV. 

Dat klopt bij nader inzien maar gedeeltelijk volgens mij, want de meeste 'afdelingen' zijn subentiteiten van vzw's, en vallen als dusdanig buiten de standaard voor 'FeitelijkeVerenigingen'. Een feitelijke vereniging zal minder snel van haar afhankelijke subentiteiten kennen (al lijkt het mij wel mogelijk). 

Willen we afdelingen van vzw's dus goed modelleren in OSLO, dan is volgens mij uitwerking nodig van de class 'Vereniging', die er nu nog niet is.
