### ISSUE TITLE
Benaming Verantwoordelijke

### ISSUE THREAD

**Issue by YvesMeersmans** [Informatievlaanderen/OSLOthema-feitelijkeVerenigingen#46]
Een verantwoordelijke heeft een bepaalde positie in een Feitelijke Vereniging. De naamgeving van de klasse Verantwoordelijke kan verwarrend zijn, vandaar dat dit eventueel aangepast zou worden naar ‘vertegenwoordiger’. 
Zijn er andere suggesties?

Mogelijke alternatieven:
- Sport Vlaanderen gebruikt ‘functie’, zonder definitie. Het is een neutrale naam.
Is dit een alternatief voor rol of voor verantwoordelijke? Een verantwoordelijke is iemand binnen de Feitelijke Vereniging. Een rol is een secretaris, oprichter, voorzitter, …
Als rol gebruiken ze de functie.

- ‘Vertegenwoordiger’, ‘aanspreekpunt’ en ‘contactpersoon’ worden bekeken als mogelijk alternatief voor ‘verantwoordelijke’.

**Comment by eveliendh** [comment]
"vertegenwoordiger" is duidelijk vind ik . De hoedanigheid "contactpersoon" lijkt me ook belangrijk. Dat kunnen 2 verschillende hoedanigheden zijn. Deze hoedanigheden worden dan ingevuld door iemand die een bepaalde rol/functie inneemt zijde "secretaris" bijvoorbeeld

**Comment by YvesMeersmans** [comment]
De suggestie om Verantwoordelijke te hernoemen naar Vertegenwoordiger wordt overgenomen.
