### ISSUE TITLE
Benaming Activiteit

### ISSUE THREAD

**Issue by YvesMeersmans** [Informatievlaanderen/OSLOthema-feitelijkeVerenigingen#47]
‘Activiteit’ erft over van OrganisatieActiviteit. In het model doelen we op de soort activiteiten die de feitelijke vereniging organiseert. Wordt ‘activiteit’ juist gebruikt of is ‘verenigingstype’ of ‘verenigingssoort’ een betere keuze? Hoe verwoorden we het best het type van activiteiten dat een feitelijke vereniging aanbiedt?
	
Mogelijke antwoorden:
‘Werking’, ‘aanbod’, ‘type activiteit’, ‘event’, een lijst van activiteiten, … worden bekeken als mogelijke alternatieven.

Er zal tevens moeten nagekeken worden of deze naamswijziging, terwijl de definitie grotendeels hetzelfde blijft, in lijn is met de OSLO richtlijnen.

**Comment by YvesMeersmans** [comment]
Als toevoeging op mijn laatste bemerking. De nieuwste definitie die momenteel op tafel ligt is "het werk van personen, een groep of een organisatie om een bepaald onbaatzuchtig doel te bereiken, in het domein waarbinnen een feitelijke vereniging actief is."

**Comment by eveliendh** [comment]
Misschien gewoon doel van de feitelijke vereniging. Ik haalde volgende uit eerdere verslagen van de werkgroepen: "•	Activiteit in dit sneuvelmodel dient begrepen te worden als de groepering (of categorisering) van de doelen van de feitelijke vereniging, eerder dan de evenementen die de vereniging organiseert. "

**Comment by YvesMeersmans** [comment]
De attributen _naam_ en _beschrijving_ zijn opgenomen in de klasse _PubliekeDienstverlening_ in het OSLO FV applicatieprofiel.

**Comment by YvesMeersmans** [comment]
De usageNote bij activiteit is nu "De Activiteit van een FeitelijkeVereniging kan bv. zijn 'jeugdvereniging', 'sportvereniging', 'seniorenvereniging', ... De FeitelijkeVereniging is actief in dit soort werking.". Daarmee wordt duidelijk gemaakt hoe activiteit in de context van OSLO FV kan begrepen worden. 
Indien de naam aangepast moet worden, dient dit besproken te worden in een toekomstige werkgroep.
