### ISSUE TITLE
Subklasse "Persoon" gebruiken in plaats van "Agent"?

### ISSUE THREAD

**Issue by eveliendh** [Informatievlaanderen/OSLOthema-feitelijkeVerenigingen#5]
"Persoon", subklasse van "Agent" lijkt meer gepast om de personen achterliggend aan feitelijke verenigingen te modelleren? Gezien feitelijke verenigingen - omwille van hun beperkte structuur - terug gebracht worden tot personen, waarvan het belangrijk zal zijn de naam, id (RRNR) te capteren (in functie van de identificatie). Deze personen kunnen via een bepaalde "Role" wel terug gelinkt worden met de feitelijke vereniging.

Feitelijke vereniging -> has member (= person) -> person holds post/role (different types) in de feitelijke vereniging

**Comment by jeroen-devlieghere** [comment]
mee eens, klopt voor mij ook niet dat Agent in het schema direct een organisatie kan zijn, is beter een Persoon.
Het is wel zo dat zo'n persoon afgevaardigd kan zijn, dus een een rol kan hebben in een 'bovenliggende' GeregistreerdeOrganisatie. Dat moet dan misschien ook in het model gerepresenteerd worden

**Comment by eveliendh** [comment]
Agent kan zowel een persoon als een organisatie zijn, het is dus "vollediger", maar abstracter + attributen zijn anders voor persoon dan wel organisatie. Dit moeten we verduidelijken in het model dan, bv screen shot ->
![image](https://user-images.githubusercontent.com/86357795/146324221-fc3af295-6ceb-4710-9743-a0dc1f139fa3.png)

**Comment by edrore** [comment]
De klasse Agent wordt behouden. Deze is vollediger. De opsplitsing naar Organisatie en Persoon zit in model vervat, via de toevoeging van OSLO-Organisatie::Organisatie en OSLO-Persoon::Persoon.
