### ISSUE TITLE
Erkenning als eigenschap van de feitelijke vereniging, erkenningsaanvraag als onderdeel van (publieke) dienstverlening?

### ISSUE THREAD

**Issue by eveliendh** [Informatievlaanderen/OSLOthema-feitelijkeVerenigingen#6]
In functie van dienstverlening (en/of andere use cases) is het relevant om te weten of de feitelijke vereniging erkend is (welke erkenning, en door wie uitgegeven). De erkenningsaanvraag capteert echter het proces dat voor de erkenning/niet erkenning komt. Dit proces lijkt me eerder thuis te horen in een model rond publieke dienstverlening. Ik verwijs hierbij bijvoorbeeld naar het model rond publieke dienstverlening (momenteel in opmaak op federaal niveau):
https://belgif.github.io/thematic/models/public%20services/index_en.html

**Comment by jeroen-devlieghere** [comment]
cfr. bespreking tijdens en na de werkgroep-bijeenkomst op 25-januari '22: 'erkenningen' moet explicieter ingebed worden in bestaande OSLO-model rond [Publieke Dienstverlening](https://data.vlaanderen.be/doc/applicatieprofiel/dienstencataloog/) (geen noodzaak dus om het federaal te gaan zoeken ;-)

Op dit moment vind ik in het AP geen indicatie terug dat 'erkenning' een subclass (of instantie) van PubliekeDienstverlening zou zijn

**Comment by YvesMeersmans** [comment]
Het blijft relevant om Erkenningsaanvraag mee te nemen in de standaard. Er kan zo een relatie worden gemaakt met PubliekeDienstverlening (uit OSLO-Dienstencataloog). De Usage note zal daarbij het volgende vermelden: "De dienstverlening vormt een aanbod (dat niet noodzakelijk wordt gebruikt). Ze houdt niet noodzakelijk het opnemen van een recht in, de dienstverlening kan de gebruiker ook toelaten een verplichting te vervullen." Een PubliekeDienstverlening vereist een Bewijs, en volgt een Procedure. Deze aspecten zijn terug te vinden in de Erkenningsaanvraag. Er zal verder onderzocht worden of een concrete overerving dient plaats te vinden.
