### ISSUE TITLE
Kardinaliteit adresvoorstelling: 1 of meer adressen mogelijk?

### ISSUE THREAD

**Issue by eveliendh** [Informatievlaanderen/OSLOthema-feitelijkeVerenigingen#7]
Het lijkt me mogelijk dat een feitelijke vereniging 1 of meerdere adressen kan hebben? Nu staat de kardinaliteit op 1.

**Comment by jeroen-devlieghere** [comment]
Ik sluit me aan bij Evelien: nu is adres mogelijk te beperkend. 
Dit botst bv. met hoe Sport VL met adresgegevens omgaat, bij hen is dat meer gelaagd: een officieel correspondentieadres, naast het adres van de hoofdvestiging en van de overige vestigingen, en daarnaast ook nog een aanduiding van het 'werkingsgebied' (één of meerdere gemeentes). 

Vraag is dus of er niet meer fijnmazigheid nodig is hier, dan louter de kardinaliteit aan te passen.
Zie ook het [AP 'Organisatie Basis'](https://data.vlaanderen.be/doc/applicatieprofiel/organisatie-basis/), dat een adres toekent aan een Organisatie én aan zijn vestigingen. 
Kan Feitelijke Vereniging dus niet beter ook de entiteit Vestiging gebruiken die aan Organisatie hangt (gezien Feitelijke Vereniging toch een subclass van Organisatie is)

**Comment by jeroen-devlieghere** [comment]
> daarnaast ook nog een aanduiding van het 'werkingsgebied' (één of meerdere gemeentes).

aanvulling: met name de uitbreiding 'werkingsgebied' zou belangrijk kunnen zijn, omdat het toelaat de link te leggen naar dienstverlening van overheden, die op het lokale niveau ook gebiedsgebonden is. Bv. een service als 'informeren op maat' zal o.a. op deze informatie steunen (louter adresinformatie is dan te beperkend)

**Comment by YvesMeersmans** [comment]
Het attribuut ‘heeftPrimaireVestiging’ is opgenomen bij de toegevoegde klasse OSLO-Organisatie::Organisatie. Die Vestiging heeft ook een vestigingsAdres. 

Het attribuut ‘adres’ staat niet meer in het model. De klasse OSLO-Organisatie::Vestiging vangt dit op. Via Organisatie kunnen Vestigingen meegegeven worden. Het is dus mogelijk om meerdere adressen mee te geven.
