### ISSUE TITLE
De geregistreerde organisatie heeft naast een voorkeursnaam ook een formele naam?

### ISSUE THREAD

**Issue by eveliendh** [Informatievlaanderen/OSLOthema-feitelijkeVerenigingen#8]
De voorkeursnaam interpreteer ik als de naam waarmee de organisatie wil "aangesproken" worden, deze kan verschillend zijn van de formele naam (bv zoals gekend in KBO). Nemen we dit ook mee in het model?

**Comment by jeroen-devlieghere** [comment]
Evelien ik kan dit volgen, dit is een beetje zoals de officiële naam versus roepnaam van mensen - lijkt me nuttig.
maar dit gaat volgens mij in tegen wat er bij #9 en #20 wordt voorgesteld (al kan ik daar niet helemaal volgen :-)

**Comment by jeroen-devlieghere** [comment]
voor de volledigheid: ik zie dat het organisatieregister nu de volgende namen onderscheidt:

- formele naam
- roepnaam
- formele korte naam

**Comment by eveliendh** [comment]
En: Engelse naam, Franse naam, Duitse naam, Spaanse naam, Formele naam volgens KBO (automatisch gevoed bij koppeling) :)

**Comment by YvesMeersmans** [comment]
Het verschil tussen voorkeursnaam en de formele naam van een organisatie wordt meegenomen in het model. Het attribuut “wettelijkeNaam” wordt toegevoegd aan Geregistreerde Organisatie, om juist hergebruik van OSLO-Organisatie te verzekeren.
