### ISSUE TITLE
Erkenning: Erkenningstype kan zowel door een naam als een code omschreven worden

### ISSUE THREAD

**Issue by eveliendh** [Informatievlaanderen/OSLOthema-feitelijkeVerenigingen#9]
Eventueel nog een verfijning m.b.t. attribuut erkenning: hiervan willen we de naam (bv. erkend als "Sportvereniging") bijhouden alsook de eventuele code (bv. erkenningstype code "20"). Dit naast de (publieke) organisatie die de erkenning uitgeeft natuurlijk. Voorgaand voorbeeld vond ik terug in de publieke lijst van erkennende verenigingen van Stad Gent: https://data.stad.gent/explore/dataset/erkenningen-verenigingen-gent/table/?sort=lastchgdatetime. Ook het model dat federaal in ontwikkeling is m.b.t. organisaties refereert naar een "code" voor wat betreft "authorizations".

**Comment by YvesMeersmans** [comment]
De mogelijkheid tot de opties ‘naam’ en ‘code’ bij Erkenningstype (opties die in sommige use cases voorkomen) worden toegevoegd als een Usage note bij Erkenningstype. De naam is dan bv. Erkend als “Sportvereniging” en de code is bv. “20”. Deze code is een fictieve code, die bv. wel betekenis kan hebben bij een publieke organisatie die een erkenning uitgeeft. Zo wordt de use case van sommige organisaties opgevangen die ook met codes werken als onderdeel van Erkenningstype
